version: '3.4'

services:
  app:
    image: stor
    container_name: app-store
    build:
      context: .
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings
    env_file:
      - .env
    # ports:
    #   - "${APP_PORT}:8000"
    networks:
      - backend
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: ${DB_HOST}
    env_file:
      - .env
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - backend
    # ports:
      # - "${APP_PORT}:5432"

  worker: &worker
    image: stor
    container_name: worker
    volumes:
      - ./src:/app/src
    entrypoint: ["/app/src/start_worker.sh"]
    depends_on:
      - app
      - redis
    networks:
      - backend
    env_file:
      - .env

  scheduler:
    <<: *worker
    container_name: scheduler
    entrypoint: ["/app/src/start_scheduler.sh"]

  redis:
    container_name: ${REDIS_HOST}
    image: redis:alpine
    volumes:
      - './data/redis:/data'
    networks:
      - backend

networks:
  backend: